CREATE SEQUENCE naplo_sqe INCREMENT BY 1 START WITH 1;

SELECT * FROM (SELECT hivasId FROM HIVAS ORDER BY idopont desc) WHERE ROWNUM <= 1;

CREATE OR REPLACE TRIGGER feltoltnaplo AFTER insert ON HIVAS 
DECLARE
sor hivas%ROWTYPE;
BEGIN
 SELECT * INTO sor FROM HIVAS WHERE hivasId = (SELECT * FROM (SELECT hivasId FROM HIVAS ORDER BY idopont desc) WHERE ROWNUM <= 1);
 
 IF (sor.mentotkuld = 1) then
  INSERT INTO NAPLO VAUES (naplo_sqe.nextval, SYSDATE + 300, SELECT USER FROM DUAL, sor.hivasId);
 END IF;

END;
